repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make black
        types: [python]
        additional_dependencies: [black==20.8b1]
        language: python
        stages: [push, commit]
      
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.2
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: local
    hooks:             
    - id: flakehell
      name: flakehell
      entry: make lint
      types: [python]
      language: python
      additional_dependencies: [flakehell==0.9.0]
      stages: [push, commit]