name: Integración continua

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Installing and configuring poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Installing dependencies
        run:  poetry install
      
      - name: Running test and coverage
        run: make cov
      
      - name: Running linter
        run: make lint